### ISSUE TITLE
演習課題 vol. 3

### ISSUE THREAD

**Issue by ms2sato** [hamika/ocs#10]
## Carクラスを作る
下記の3つのプロパティ（メソッドのことです）を持つ Carクラスを作りましょう。
- メーカー
- 重さ
- 色

## Carクラスのコンストラクタを作る
```rb
car = Car.new('toyota', 5000, 'red')
```
上記のように new できるようにコンストラクタを作りましょう。

## 沢山のCarクラスを扱う

```rb
cars = [
  Car.new('toyota', 5000, 'red'),
  Car.new('honda', 4560, 'blue'),
  Car.new('toyota', 3200, 'green')
]
```

上記の carsにて、下記の課題をやりましょう。

- [x] 全ての車の合計の重さ、平均の重さを計算する
- [x] メーカー、重さ、色の順にputしましょう（ toyota, 5000, red のような行が3行出ます ）
- [x] 上記のputsでredの場合には赤、blueの場合には青、greenの場合には緑と出しましょう
- [x] 一番多いメーカーを計算で出す

**Comment by hamika** [comment]
@ms2sato 1問目解けました! => e6149bf
 一応 `cars` の中身が増えても合計と平均が出せるように書いてみました。

**Comment by hamika** [comment]
@ms2sato 2問目解けました。 => 542a6e6 
ブロックの中からputsするだけで良かったのでしょうか?

**Comment by hamika** [comment]
@ms2sato 3問目解けました。 => 7b432be 
`.gsub` を使ったのですが、邪道だったらやり直します。

**Comment by hamika** [comment]
@ms2sato 4問目も解けました。 => e6fe2ac 
お手隙の際にご確認よろしくお願い致します。

**Comment by hamika** [comment]
@ms2sato Q3もQ4もうまい処理の方法がわかりません。
何かヒントいただけますか？宜しくお願い致します。

**Comment by ms2sato** [comment]
@hamika コメントしておきました。見てみてくださいね。

**Comment by hamika** [comment]
@ms2sato この課題とは全然関係ないですけど、配列を利用して [百ます計算](https://ja.wikipedia.org/wiki/%E7%99%BE%E3%81%BE%E3%81%99%E8%A8%88%E7%AE%97) というのを作ってみたくなって `handred.rb` というファイルに作ってみました。 => 350f2fc 
生成される乱数を一意のものにするなど直したい箇所は色々ありますが、取り敢えず動かせるようになったので上げておきます。

**Comment by hamika** [comment]
@ms2sato 時間かかりましたが `.sort` を使ってやっと昇順 <=> 降順でレコード並べ替えて動かせました。色々なキーワードで調べて、結局公式ドキュメントが一番参考になった気がします。

[instance method Hash#sort](https://docs.ruby-lang.org/ja/latest/method/Hash/i/sort.html)

レコードの件数を増やして動かしてみたので、きちんと実装できていると思います。お手隙の際にご確認お願い致します。あと `min, max`で取れる値が間違っているのはハッシュで使った場合、キーで並べ替えた配列を返してしまうので、ブロックに明示的に書く必要があると今読んでいる本で見かけたので試してみました。この認識で合っていますでしょうか？

```ruby
puts "#{ company_to_count }"
#=> {"toyota"=>5, "honda"=>3, "mazda"=>2, "suzuki"=>2, "subaru"=>3, "nissan"=>1}
puts "#{ company_to_count.max { |a, b| a[1] <=> b[1] } }\t#{ company_to_count.min { |a, b| a[1] <=> b[1] } }"
#=> ["toyota", 5]	["nissan", 1]
puts "#{ company_to_count.max }\t#{ company_to_count.min }"
#=> ["toyota", 5]	["honda", 3]   # これだとキーのアルファベット順で表示している
```

**Comment by ms2sato** [comment]
@hamika 素晴らしい！ よく書けました！

> min, maxで取れる値が間違っている

先の回答のことですよね。 あの時は `tmp.keys.max` `tmp.values.max`のようにkeys、valuesを介して最大を計算していました。これらの意味は理解しておけると良いです。それぞれどんな値を計算してしまったでしょうか。

ブロックを使っている意味についての理解は合っています。ここでのブロックは、並べ替えの条件をプログラマーが自分で指定するために利用しています（ブロックは様々な意味合いで使われます。 eachなどでも使っていますよね。どんなメソッドで利用されるかで意味が変わるので注意です）。
