### ISSUE TITLE
2. 顧客管理画面を作成する

### ISSUE THREAD

**Issue by ms2sato** [hamika/ocs#11]
今進めているActionPlan、Scheduleの方で手が空いてしまったらやります。

顧客に関してCRUDできる画面を作りましょう。
- [x] テーブルのカラムを決める（このIssueに決めたことを書き込んでください）
- [x] Scheduleなど関連するテーブルへのリレーションを作成する
- [x] CustomerをCRUDできる画面を作成する
- [x] Customer指定をしなければいけない画面があれば対応する（Schedule作成など）

**Comment by ms2sato** [comment]
@hamika そろそろ先も必要かと思うので、やってみましょう。多分自己判断で進められるところも多くなってきたと思うので、その辺りは進めてしまって大丈夫です。不安があれば確認メッセージいただければ拝見しますー。

**Comment by hamika** [comment]
![erd](https://user-images.githubusercontent.com/25607855/28369538-e4f4fcc4-6cd2-11e7-9498-1823d52bd068.png)

**Comment by hamika** [comment]
@ms2sato 

## Customer Table

| カラム名 | 型 | 説明 |
| :--- | :--- | :--- |
| `id` | `integer` | ID |
| `first_name` | `string` | 名 |
| `last_name` | `string` | 姓 |
| `address` | `string` | 住所 |
| `phone` | `integer` | 電話 |
| `email` | `string` | Eメール |
| `birthday` | `date` | 誕生日 |
| `gender` <br> `0: male` <br> `1: female` | `integer` | 性別 |

こんな感じで考えています。

**Comment by ms2sato** [comment]
@hamika 

`phone` は string で行きましょう。 先頭の0が入らなくなってしまったりします。
その他は良いと思います！進めて大丈夫です！

**Comment by hamika** [comment]
@ms2sato お疲れ様です。
#13 ははまってしまって進まないので、こっちやっていきます。
Customers Table作成して、性別を選択できるようにしました。

f3461b9

アソシエーションを失敗したっぽいので、あとで手直しします。

### やりたいイメージ

- `Schedule` は複数の `Customers` と関連付けられる(一つの予定で複数人のお客様に会う)
- `Customer` は複数の `Schedules` と関連付けられる(一人のお客様と複数回の予定を組む)

この場合、多対多で関連付けを行えばいいのでしょうか。

**Comment by ms2sato** [comment]
@hamika こっちは今までの延長なので、ガンガン行きましょう！

> この場合、多対多で関連付けを行えばいいのでしょうか。

その通りです！
今のアソシエーションもよく書けていたと思うので残念ですが、これも練習なので一度戻す（新しくマイグレーションを追加して戻しましょう）流れでやりましょう。

次の報告待っていますー

**Comment by hamika** [comment]
@ms2sato ありがとうございます。
多対多の関連付けは2種類あるようなのですが、どちらにすればいいのでしょうか？

[2.8 has_many :throughとhas_and_belongs_to_manyのどちらを選ぶか](https://railsguides.jp/association_basics.html#has-many-through%E3%81%A8has-and-belongs-to-many%E3%81%AE%E3%81%A9%E3%81%A1%E3%82%89%E3%82%92%E9%81%B8%E3%81%B6%E3%81%8B)

今回の場合だと、中間テーブルはいらないかなと思ったので `has_and_belongs_to_many` でいいのかなという感じがしたのですが。

**Comment by hamika** [comment]
今回の場合だと中間テーブルはいらないかなと思ったので `has_and_belongs_to_many` いいかという感じがしたのですが。

**Comment by ms2sato** [comment]
@hamika 現場では今はほとんど `has_many :through` が使われるので、 そちらをオススメします！

**Comment by ms2sato** [comment]
@hamika 多分この続きで、Scheduleで顧客を関連づけるというのをやると理解しています。この続きでやりましょう。

また、 1 Issue に対して、 1PullRequest（PRと略します）に揃えると良いので、今後は意識してみてください。
