### ISSUE TITLE
3. ポイント付与を実装する

### ISSUE THREAD

**Issue by ms2sato** [hamika/ocs#12]

**Comment by hamika** [comment]
@ms2sato お疲れ様です。
こんな感じでやろうと思っています。

## やりたいこと

1. `ActionPlan` を新規作成すると `activity` の目標ポイントが設定される。
  1.1. `:action_plan.target` に入力した目標件数 **`1`** に対して `activity` が **`10`** ポイント(10倍)
2. `/schedules/:id/edit` でチェックボックスから `activities` のポイント種別を選択

| 名称 | ポイント |
| :--- | :--- |
| `setup` | 2pt |
| `interview` | 2pt |
| `inspection` | 3pt |
| `presentation` | 2pt |
| `engagement` | 1pt |

全部の項目をクリアすると10ptになるイメージです。

3. `activity` ポイント獲得状況と `action_plan.target` (目標件数)を比較
4. `activity` ポイント獲得状況と `schedule.target` (結果件数)を比較

## 実際に実装すること

1. Schedule Tableに `activity` カラムを追加
3. `/schedules/:id/edit` で `enum` を使って `activities` のチェックボックスを実装する。
  3.1. こんなイメージ => `enum activity: { setup: 2, interview: 2, inspection: 3, presentation: 2, engagement: 1 }`
4. `/dashboards?action_plan_id=xxx` で上記やりたいこと `3` と `4` を実現

**Comment by ms2sato** [comment]
@hamika ありがとうございます。ちょっと確認させてください。

Scheduleと、`enum activity` のactivity は一対一対応になりますか？`Schedule`が`activity`カラムを持つということは、基本的には `schedule.activity = :setup` や、 `schedule.activity = :interview` のようにならないといけないのです（enumはそういう「一つのステータスを設定する方法だと思ってください」）。

チェックボックスで実装すると書かれているから、そうでは無いかも？と思っています（複数チェックが可能ですよね）。

もしも一つのScheduleには複数の（例えば :setupと:interviewなど）activityが含まれる場合であれば、一回仕様をもう少し簡単な方へ考えたいです。多分実装が大変になってしまうので、一度簡単な方向で進めて余裕があれば直す方が良さそうです。

## 提案
Scheduleテーブルに、 下記のようなbooleanのカラムを作りましょう。そしてチェックボックスでチェックしたらtrueになるようにすると良いと思います。

- activity_setup
- activity_interview
- activity_inspection
- activity_presentation
- activity_engagement

## その他アドバイス
`enum activity: { setup: 2, interview: 2, inspection: 3, presentation: 2, engagement: 1 }`

`enum` は、数字の部分がactivityカラムの値として保存されます。setupを設定すると2という数値がactivityカラムに保存される仕組みです。上記の書き方だと、interviewもpresentationも2で保存されてしまうので、今回のやりたい事には適さないのです。

enumが効果を発揮するのは「何かの状態を一つ決める場合」だと思ってください。例えば下記のように、営業の段階を0から3までの4段階で表される時には使いやすいです。これで、ある営業の状態がleadなのか、presalesなのか、という状態を検索することができます。

`enum status: { lead: 0, presales: 1, sales: 2, engagement: 3 }`

## 最後に
システムの提案としては凄く良くなってきています。テーブル構造と、実際のUIのイメージまでできているのでまとまっていると思います。あと、私が求める仕様を勘違いしているかもしれないのでもしそんな感じがあったら意見くださいね。

**Comment by hamika** [comment]
@ms2sato ありがとうございます。
@ms2satoさんがイメージしているのと僕のイメージはぴったりあっています(実は私の説明不足で伝わらなかったらどうしようと思っていました)
今回イメージしているのは、

> 1. `User` が `ActionPlan` を作成
> 2. `:target` を1件追加するごとに10pt分の `activities` が発生
> 3. `Schedule` で `activities` をこなして10ptをクリア
> 4. `/dashboards` で進捗を確認

のような感じです。なのでSchedule Tableに、

- [ ] activity_setup
- [ ] activity_interview
- [ ] activity_inspection
- [ ] activity_presentation
- [ ] activity_engagement

カラムを追加する方法でやってみます => 取り敢えずカラム追加しました。 568a682

**Comment by hamika** [comment]
@ms2sato 
取り敢えずカラム追加しました。

568a682

**Comment by ms2sato** [comment]
@hamika 内容が合っている様子で良かったです。ではこのまま進めて行きましょう。

**Comment by hamika** [comment]
@ms2sato おはようございます。
すごい冗長な処理な気がしますが、activitiesを保存変更できるようになりました。

563578d

お手隙の際にご確認、お願い致します。

**Comment by hamika** [comment]
@ms2sato 健忘用。ケータイで書いてるので間違ってたらすみません。

`/dashboards` 上で 

```ruby
# 例:
action_plan = ActionPlan.find(xxx)
action_plan[:target]  #=> 3
ap_target = ActionPlan[:target] * 10 #=> 30

schedule = Schedule.where(action_plan_id: xxx)
s_target = 0
schedule.each do |s|
  s_target += s.target
end
s_target = s_target * 10 #=> 50
```

`ap_target` や `s_target`  と `Schedule.where(action_plan_id: xxx)` で引っ張ってきたactivityの合計ポイントを計算して進捗を作りたいと思っていますー

**Comment by hamika** [comment]
`s`は`s.target`でした。

**Comment by ms2sato** [comment]
@hamika 概ねやりたいことを理解しました。

> ap_target = ActionPlan[:target] * 10 #=> 30

> s_target = s_target * 10 #=> 50

この辺りで10を掛けているのは 最大を100にしたいとかそういう感じですかね？あとで教えてください。

書いてくれたコードはもう少し調整できそうですが、流れとしてはその形で良さそうです。

**Comment by ms2sato** [comment]
@hamika 上記コミュニケーションできてなかった orz... 。 上の件どうですかね。また、実装は進めて大丈夫と思います！

**Comment by hamika** [comment]
@ms2sato わかりにくかったですね! すみません。
`ActionPlan.target` で設定した目標件数の10倍がactivitiesの初期値(こなすべき活動量)なので `ap_target = ActionPlan.target * 10` と activitiesの合計ポイントを割り算してパーセント表示して... 進捗率が出せればいいかなと思っています。
dashboards_controllerですでにある変数なども使い回せそうなので、うまくできたらと思っています。
s_target... は僕の計算間違いというか、勘違いでした!
