### ISSUE TITLE
1. Scheduleを検索する

### ISSUE THREAD

**Issue by ms2sato** [hamika/ocs#13]
- [x] Achevement の完全一致で検索する
- [ ] 期間の開始、終了で検索する
- [ ] ActiveRecordのscopeについて調べる
- [ ] scopeを使ってみる

**Comment by ms2sato** [comment]
@hamika うまく動かない時に心がけること。

1. 闇雲にコードを変えない。見たことのない文法に変えない。
2. 「いつもやっていることと同じ部分」「いつもとは違う部分」を分けて考えてみる。
3. `p` や `put` 、 ターミナルのログを見る。今どんな動きをしているのかを「確認する」。想像でやらない。

**Comment by hamika** [comment]
@ms2sato よく気をつけて心がけます。

**Comment by hamika** [comment]
@ms2sato お疲れ様です。
`term_from` の検索フォーム

```ruby
controller
@schedules = Schedule.where(term_from: params[:term_from])

view
<%= form_tag '/schedules', method: 'get' do %>
  <div class="field">
    <%= datetime_select :term_from, params[:term_from] %>
    <%= submit_tag %>
  </div>
<% end %>
```

上記で表示はされるようになったのですが、検索をすると
can't cast ActionController::Parametersとブラウザに表示されて、
サーバーにもSchedule Load (0.4ms)  SELECT "schedules".* FROM "schedules"
という表示になってしまいます。これはcontrollerの条件指定の書き方が間違っていて、 `term_from` 値が渡されていないのかなと思ったのですが、認識合っていますでしょうか？

**Comment by ms2sato** [comment]
@hamika その実装の仕方もよくわかる！よくわかるんだけど、多分その方法はちょっと大変。

例えばまず一回これだけやりませんか？

- 年のドロップダウンボックスだけを作る（... 2015、2016、2017 ... のようなものが選べる）
- 年を選択して、その年のものだけ検索可能にする

**Comment by hamika** [comment]
@ms2sato お疲れ様です。

```ruby
<controller>
@schedules = Schedule.where(params[:date][:year])

<view>
<%= form_tag '/schedules', method: 'get' do %>
  <div class="field">
    <%= select_year(Time.now) %>
    <%= submit_tag %>
  </div>
<% end %>
```

とすると年のドロップダウンボックスだけ作成されたのですが、送信すると `PG::DatatypeMismatch: ERROR:  argument of WHERE must be type boolean, not type integer` というエラーが出てしまいます。

ターミナルのログを見ると `Parameters: {"utf8"=>"✓", "date"=>{"year"=>"2017"}, "commit"=>"Save changes"}` と出ているのでcontrollerで値を取り出す書き方が間違っていて、boolean?になるようにしなくてはいけないのかなと類推していますが、認識あっていますでしょうか。

**Comment by ms2sato** [comment]
@hamika 連絡ありがとうございます。

- `where` の書き方についてですが、こういう書き方で他もやっていましたか？比較してみてください。ここが修正されれば、`booleanでなければならない`とは言われなくなるはずです。

「年」だけ渡すことができたとして、実際にDBに入っているのはdatetime型です。年の数字だけではdaettimeは検索することができません。Time型かDateTime型を「年」の値から作らないと行けないです。

例えば2017年だけを指定されたとして、 欲しいデータは 2017/1/1 0:00 - 2017/12/31 23:59 の間ですね。これを実現するにはどうしたら良いでしょうか。

もう少しやってみて、難しそうなら一度保留しましょうね。

**Comment by hamika** [comment]
@ms2sato ありがとうございます。

```ruby
<controller>
@schedules = Schedule.where(term_from: params[:year])

<view>
<%= form_tag '/schedules', method: 'get' do %>
  <div class="field">
    <%= select_year Time.now, prefix: :term_from %>
    <%= submit_tag %>
  </div>
<% end %>
```

と変更するとエラー表示はなくなったのですが、全く画面にどのレコードも表示されない(開始の年だけしか値を渡していないから?)状態になりました。
ログには `Parameters: {"utf8"=>"✓", "term_from"=>{"year"=>"2017"}, "commit"=>"Save changes"}` と `Schedule Load (0.4ms)  SELECT "schedules".* FROM "schedules" WHERE "schedules"."term_from" IS NULL` と出ています。
エラーが出ていないのでわからないのですがこれ、エラーじゃないけど値の取得できていないよってことなのでしょうか?

> 「年」だけ渡すことができたとして、実際にDBに入っているのはdatetime型です。年の数字だけではdaettimeは検索することができません。Time型かDateTime型を「年」の値から作らないと行けないです。

それから年の値の取得ができたあとも、検索機能を作るにはterm_from, term_toそれぞれに年/月/日/時/分/秒と個別の処理を作って実装する必要がある、ということで認識合っていますでしょうか。

```ruby
<イメージ>
. . . 
<%= select_year Time.now, prefix: :term_from %>
<%= select_month Time.now, prefix: :term_from %>
<%= select_day Time.now, prefix: :term_from %>
. . . 
```

**Comment by ms2sato** [comment]
@hamika おはようございます。朝早くからお疲れ様です。

```rb
@schedules = Schedule.where(term_from: params[:year])
```

この変更は良いですね！ `term_from`のように「どの要素を検索対象にするのか」を指定しないといけませんよね。

> エラーが出ていないのでわからないのですがこれ、エラーじゃないけど値の取得できていないよってことなのでしょうか?

端的に言うと、答えはNOです。エラーの場合にはERRORと表示されたり、スタックトレース（どこのコードを通ったのかの長〜い文言）が表示されたりしますよね。ここにはそう言う表示が無いと思います。
検索がうまく言っている場合でも同じようなものが表示されると思いますよ。

`Schedule Load (0.4ms) SELECT "schedules".* FROM "schedules" WHERE "schedules"."term_from" IS NULL`

ここはSQLが表示されています。今検索に使われているSQLはこう言うものですよ、と示してくれています。

正確には下記がSQLの部分です。これはSQLのうちのSELECT文という構文ですが、一度調べてみましょう。SELECTとWHEREについて理解するとここで表示されていることの意味がわかってきます。

```
SELECT "schedules".* FROM "schedules" WHERE "schedules"."term_from" IS NULL
```

> それから年の値の取得ができたあとも、検索機能を作るにはterm_from, term_toそれぞれに年/月/日/時/分/秒と個別の処理を作って実装する必要がある、ということで認識合っていますでしょうか。

UIのイメージとしてはその形で行けると思います。サーバー側は少し工夫が必要になるでしょう。
以下のように一つずつ分解しましょう。

1時間ほどまずは下記に取り組んでください。1時間でできた範囲を報告いただいて、それ以外は #11 を進めましょう！

### Form 〜 Controllerについて
先の報告から、下記のようにPOSTされている情報があると思います。

```
Parameters: {"utf8"=>"✓", "term_from"=>{"year"=>"2017"}, "commit"=>"Save changes"}
```

さて、この状態で、2017を取得するには paramsにどのようにアクセスすれば良いでしょうか。
puts で2017が表示できればOKです。今書いているコードで2017が出るでしょうか。

### 期間で検索をする
`rails c` を使って、検索をしてみましょう。 どのようにすると検索できるでしょうか。「ActiveRecord 検索 期間」などと入れてWEB検索すると良い情報が出るかもしれません。

### 上の二つができたら結合する
上記2つができていれば、それを繋ぐことを考えます。

**Comment by hamika** [comment]
@ms2sato 先に `rails c` でできた部分だけまとめます。すみません、まとまった時間が確保できなかったので**Form 〜 Controllerについて**と**期間で検索をする**はもう少し(1時間分)やってみて報告します。

```ruby
paramaters = {"utf8": "✓", "term_from": {"year": "2017"}, "commit": "Save changes"}
=> {"utf8"=>"✓", "term_from"=>{"year"=>"2017"}, "commit"=>"Save changes"}
paramaters[:term_from]
=> nil
paramaters["term_from"]
=> {"year" => "2017"}
paramaters["term_from"]["year"]
=> "2017"
paramaters["term_from"]["year"].to_i
=> 2017
```

`rails c` でログと同じ内容の変数を作って取り出すだけなら簡単にできるのですが、DBから取り出すのは手強いです。。。

**Comment by ms2sato** [comment]
@hamika 良いですね！ 上記で確かめられたこと。

```rb
paramaters["term_from"]["year"].to_i
```

のようにすれば、年は数値で取れる、ということですね。次はこれをコントローラの中で確認してみて下さい。コントローラの中で動かすと、ひょっとすると文字列のキーではなくて、シンボルでないと動かないかもしれません（Railsではよくそういうことがあります。それも確認して下さい）。

「formでGETパラメータで送られた値を、Controllerの中で取れること。その方法。」を確かめます。

確かめられたら、これをまず信じる。もしうまく動かなくてもここ無闇にいじらない。そうやって「確認できたこと」を固定していくイメージです。拠り所がないとあれもこれも違っている気がして弄ってしまうから、正しいと思うところを決めていきます。

そして、ここまででやれたのは「Form 〜 Controllerについて」というところです。だからDBとは`全く無関係です`よね？

ここまでできたら、 https://github.com/hamika/ocs/issues/13#issuecomment-325240685 で書いた次のステップへ進みます。次は 「DB側はどうなっていれば良いのか」確かめましょう。具体的には

> 期間で検索をする

をやってみましょう。これがDB側の動きを確認する手段です。
一個ずつ思った通り動いているところを確認したり、思った通り動かす方法を確認していって下さい。小さい単位なら簡単な法則で動いているだけなので、確認しやすいです。

**Comment by hamika** [comment]
@ms2sato お疲れ様です。

期間の指定はこのあたりが適当なのでしょうか。

```ruby
irb(main):031:0> Schedule.where(term_from: Time.zone.today.beginning_of_year..Time.zone.today.end_of_year).to_sql
=> "SELECT \"schedules\".* FROM \"schedules\" WHERE (\"schedules\".\"term_from\" BETWEEN '2017-01-01' AND '2017-12-31')"
irb(main):032:0> Schedule.where(term_from: Time.zone.today.beginning_of_year...Time.zone.today.end_of_year).to_sql
=> "SELECT \"schedules\".* FROM \"schedules\" WHERE (\"schedules\".\"term_from\" >= '2017-01-01' AND \"schedules\".\"term_from\" < '2017-12-31')"
```

[ActiveRecordで日付・時刻の範囲検索をシンプルに書く方法](https://techracho.bpsinc.jp/hachi8833/2016_08_19/24876)

**Comment by ms2sato** [comment]
@hamika 良いですね！

そうすると、今回はUIからは「年」が数値で渡される予定です。
年の数値をどのように加工すれば

```
Schedule.where(term_from: Time.zone.today.beginning_of_year..Time.zone.today.end_of_year)
```

のような検索にすることができるでしょうか。

今やっているのは「問題を分解して小さくする」ということをしています。小さな問題に分解して解いた結果を組み合わせます。

**Comment by hamika** [comment]
@ms2sato おはようございます。

> formでGETパラメータで送られた値を、Controllerの中で取れること。その方法。

がまだ確かめられていません。 `/schedules` にアクセスした時の

```ruby
# view
<%= form_tag '/schedules', method: 'get' do %>
  <div class="field">
    <%= select_year Time.now, prefix: :term_from %>
    <%= submit_tag %>
  </div>
<% end %>
```

```html
/*出力されたHTML*/
<form action="/schedules" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
  <div class="field">
    <select id="term_from_year" name="term_from[year]">
. . . 
```
となっていて、ログには ` Parameters: {"utf8"=>"✓", "term_from"=>{"year"=>"2017"}, "commit"=>"Save changes"}` となっているのでcontrollerの方は

```ruby
# controller
@schedules = Schedule.where(term_from: params[:term_from][:year].to_i)
```

かなと思ったのですが、

```
PG::InvalidDatetimeFormat: ERROR:  invalid input syntax for type timestamp: "2017"
: SELECT "schedules".* FROM "schedules" WHERE "schedules"."term_from" = $1
```

とエラーになってしまい値を取得できません。
rails consoleだとうまく値を取り出せたので、同じハッシュを指定する要領でいけるかと思ったのですが、何か根本的な勘違いをしているのでしょうか?
ここをできれば `Schedule.where(term_from: Time.zone.today.beginning_of_year..Time.zone.today.end_of_year)` と組み合わせて、範囲で検索できるのかなと思っているのですが...

[4.1 ベアボーンヘルパー](https://railsguides.jp/form_helpers.html#%E3%83%99%E3%82%A2%E3%83%9C%E3%83%BC%E3%83%B3%E3%83%98%E3%83%AB%E3%83%91%E3%83%BC)
[4.4 個別のコンポーネント](https://railsguides.jp/form_helpers.html#%E5%80%8B%E5%88%A5%E3%81%AE%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88)

**Comment by ms2sato** [comment]
@hamika 

```
params[:term_from][:year].to_i
```

ここまでの値をとりあえず変数に入れてみましょう。
ここで値が取れて入れば「フォームからの年の値は取れた」と、ここまで確定できます。
@hamika さんの今の報告は「確定されたところ」がどこまでかわかりません。問題を切り分けるには、確定できるところがどこまでか判断し続ける必要があります。

> Schedule.where(term_from: Time.zone.today.beginning_of_year..Time.zone.today.end_of_year) と組み合わせて

と書かれていますが、具体的にどのようにするのか考えていますか？もしも考えているとして、どんなコードになりますか？

`year` という変数に2017が入っているとして、範囲検索ができるでしょうか。下記ではダメですよ（ダメであることは rails c すればわかるはずです）。

```
Schedule.where(term_from: year..year)
```

term_from は 「DateTime型」なので、TimeかDateTimeの型でなければ検索できません。Integerでは検索できません。rails c の状態でこの部分の検索を成功させる必要があります。

この課題はハマっている様子なので、あと一時間で一度手を引きましょう。別の課題を進める方が実りがあると思います。
