### ISSUE TITLE
バリデーションを付ける

### ISSUE THREAD

**Issue by ms2sato** [hamika/ocs#17]
各種モデルに、バリデーションを付けましょう。

- [x] バリデーションをよくわからなければ調べる
- [x] 各モデルに実装する

**Comment by hamika** [comment]
## 参考にしたリンク

[Railsバリデーションまとめ](qiita.com/shunhikita/items/772b81a1cc066e67930e)
[Rails 4でモデルのバリデーションまとめ](ruby-rails.hatenadiary.com/entry/20140724/1406145303#model-validation-definettions-length)
[Active Record バリデーション](https://railsguides.jp/active_record_validations.html)
