### ISSUE TITLE
/ のページを作成する

### ISSUE THREAD

**Issue by ms2sato** [hamika/ocs#19]
「/」 のページが今何もない実装なので、Schedule#index がトップページになるように routes.rb を修正しましょう。

**Comment by hamika** [comment]
@ms2sato 
すみません、うまくPRできなかったのですが、実装できました。
a836eb4

**Comment by hamika** [comment]
### 参考にしたURL

[ルート(/)へのルーティング設定](http://www.rubylife.jp/rails/routing/index2.html)

**Comment by ms2sato** [comment]
よくできました！
