### ISSUE TITLE
Deviseを使って、ログイン、ログアウトができるようにする

### ISSUE THREAD

**Issue by ms2sato** [hamika/ocs#2]
Railsのgemでログインログアウトを実現するのに有名なDeviseというものがあります。まず、簡単にログインログアウトを実現してみましょう。

- Userテーブルを使う例がよく引っかかると思います。同じで大丈夫です（名前を変えると一般的な方法と変わってくるので苦労が増えてしまいます。まずはよくある形をやるのがベストです）。
- `rails new` しただけのところに `devise` だけを組み込みます。

**Comment by hamika** [comment]
**以下参考にしたページを貼っておきます。**

## ~ bundle installまで
このページを見て、`$ bundle install --path vendor/bundle`でpath指定をして`$ bundle install`を行いました。

<br>

_**[rails newの先輩オススメ手順](http://maetoo11.hatenablog.com/entry/2016/03/04/144216)**_

<br>
<br>

## rails newではまった...
`$ rails new`しようとするとRailsが入っていないよとエラーが。

<br>

```
Rails is not currently installed on this system. To get the latest version, simply type:

    $ sudo gem install rails

You can then rerun your "rails" command.
```

<br>

以下のページを調べて、システムのrubyを読みにいっていることががわかったので、.bashrcに`export PATH="$HOME/.rbenv/shims:$PATH"`と追加して再度`$ rails new`したのですがなぜか上手くいかず。

<br>

_**[MacOSX-Lionでrbenvを使ってRubyOnRailsの環境構築すると、以下のようなメッセージが出てドハマリしたけど、なんとか解決したことについてのメモ(推理なので正しいかどうかの確証持てない)](http://qiita.com/w7tree/items/0860e2856f2429b20eee)**_

<br>

_**[.bash_profile ? .bashrc ? いろいろあるけどこいつらなにもの?](http://qiita.com/hirokishirai/items/5a529c8395c4b336bf31)**_

<br>

_**[本当に正しい .bashrc と .bash_profile の使ひ分け](http://qiita.com/magicant/items/d3bb7ea1192e63fba850)**_

<br>
<br>

以下のページを読んで、作業するディレクトリでrubyのバージョン指定をする必要があることを知り`$ rbenv local 2.4.1`と入力

<br>

_**[rbenvを使った場合、複数環境のRuby+Railsの組み合わせはどうインストールされるのか](http://qiita.com/fujicom/items/fe788c0f56f647fb58d8)**_

<br>

_**[rbenv を利用した Ruby 環境の構築](http://dev.classmethod.jp/server-side/language/build-ruby-environment-by-rbenv/)**_

<br>
<br>

以下のページをざっと読んで`$ rails new`を実行上手くできました。

<br>

_**[rbenv インストールから Bundler を使用した Rails のローカルインストールと起動まで](http://qiita.com/egopro/items/aba12261c053eecd6d19)**_

_**[rails new 手順書](http://qiita.com/youcune/items/312178c54c65f3ab4d42)**_

<br>
<br>

## deviseの実装
deviseの実装は以下のページを参考にしました。
Railsの命名規則のエラーではまりましたがなんとかなりました。

<br>

_**[Rails5 devise でログイン機能を実装する](http://31webcreation.hatenablog.com/entry/2016/07/31/083000)**_

**Comment by hamika** [comment]
**ActionPlan Table**と**Schedule Table**の内容。
下記のような感じにしようと思っています。

## /action_plans - 行動計画

|カラム名|データ型|viewの表示|
|:---|:---|:---|
|term_from|datetime|期間(開始)|
|term_to|datetime|期間(終了)|
|target|integer|目標額|
|achievement|integer|達成額|
|body|text|メモ|

---

## /schedules - 予定表

|カラム名|データ型|viewの表示|
|:---|:---|:---|
|term_from|datetime|期間(開始)|
|term_to|datetime|期間(終了)|
|target|integer|目標額|
|achievement|integer|達成額|
|body|text|メモ|
|destination|string|訪問先|
