### ISSUE TITLE
Customer検索を作る

### ISSUE THREAD

**Issue by ms2sato** [hamika/ocs#21]
名字、名前 それぞれと、AND検索で実現する

- [x] whereで検索する（Controller）
- [x] scopeに直す（Modelへリファクタリング）

**Comment by hamika** [comment]
@ms2sato お疲れ様です。
以下リンク等を参考にして、名前検索実装できました。

[作って学ぶRuby on Rails Vol.21 検索機能を盛り込もう！](https://blog.codecamp.jp/rails_text_21)

[Active Record クエリインターフェイス | Rails ガイド | 14 スコープ](https://railsguides.jp/active_record_querying.html#%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%97)

## whereで検索する (Controller) 完全一致

```ruby
# controller
def index
  @customers = Customer.all
  if params[:first_name].present?
    @customers = Customer.where("first_name = ?", params[:first_name])
  end
end
```

```erb
<!-- view -->
<%= form_tag(customers_path, method: "get") do %>
  <div class="field">
    <%= label_tag :first_name %>
    <%= text_field_tag :first_name, params[:first_name] %>
    <%= submit_tag %>
  </div>
<% end %>
```

```html
<!-- html -->
<form action="/customers" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
  <div class="field">
    <label for="first_name">First name</label>
    <input type="text" name="first_name" id="first_name" />
    <input type="submit" name="commit" value="Save changes" data-disable-with="Save changes" />
  </div>
</form>
```

>/customers
> ![2017-09-14 22 32 02](https://user-images.githubusercontent.com/25607855/30433652-000e8260-99a0-11e7-9bc2-11cf7f82bd7b.png)

> /customers?utf8=%E2%9C%93&first_name=fo&commit=Save+changes
> ![2017-09-14 22 32 43](https://user-images.githubusercontent.com/25607855/30433650-ff9bfe0c-999f-11e7-85d8-fbbe010a5220.png)

>/customers?utf8=%E2%9C%93&first_name=foo&commit=Save+changes
> ![2017-09-14 22 33 01](https://user-images.githubusercontent.com/25607855/30433651-ffc4348a-999f-11e7-973f-3902cb2fdb19.png)

## scopeに直す (Modelへリファクタリング) 部分一致

```ruby
# model
class Customer < ApplicationRecord
  . . .

  scope :search_first_name, ->(first_name) {
    where("first_name like ?", "%#{first_name}%")
  }
end
```

```ruby
# controller
def index
  @customers = Customer.all
  if params[:first_name].present?
    @customers = Customer.search_first_name params[:first_name]
  end
end
```

> /customers?utf8=%E2%9C%93&first_name=a&commit=Save+changes
> ![2017-09-14 23 21 11](https://user-images.githubusercontent.com/25607855/30434978-9704b0ba-99a3-11e7-91cb-4c114f581932.png)

> /customers?utf8=%E2%9C%93&first_name=f&commit=Save+changes
> ![2017-09-14 23 21 38](https://user-images.githubusercontent.com/25607855/30434980-9727bd80-99a3-11e7-8376-84abb10a5f27.png)

**Comment by ms2sato** [comment]
@hamika 概ね良さそうですね。PullRequest作って欲しかったー。基本的にコードを人に見せたいときはPullRequestを作って良いですよ。
