### ISSUE TITLE
集計画面を作成する

### ISSUE THREAD

**Issue by ms2sato** [hamika/ocs#5]
- [x] 新しい画面を表示できるようにする
  - URLなどの名前はご自身で決めて大丈夫です dashboardとかが適当でしょうか？
- 画面を表示する際に計算をする
  - [x] 指定したActionPlanのScheduleを取ってくる（例えば一週間なら5件とか取れるはず）
  - [x] 5件のデータから、実績データの合計を計算する
  - [x] 上記の実績データの合計を ActionPlanに設定された目標データと割り算して割合を出す

**Comment by hamika** [comment]
@ms2sato dashboards_controller.rbに集計画面を作る処理を作れました。 
b237a69 
お手隙の際に、ご確認よろしくお願い致します。

**Comment by hamika** [comment]
@ms2sato 
view helper 実装できました。
95c5610

**Comment by ms2sato** [comment]
終了しているのでCloseします！よくできました！
