### ISSUE TITLE
配列に入っている値を合計する

### ISSUE THREAD

**Issue by ms2sato** [hamika/ocs#6]
以下の内容をやってみましょう。Railsに載せなくても動くと思うので、array.rb のようなrubyのファイルを作成して、 `ruby array.rb` のような形で呼べるようにしましょう。

# 単純な配列の中身を合計する

```rb
array =  [4, 6, 7, 9]
result = 0

# どう書いたら良いでしょうか。

puts "結果: #{result}" #  26 が出るはず
```

# ハッシュが入っている配列の中身を合計する

```rb
array =  [{ value: 4}, {value: 6}, {value: 7}, {value: 9}]
result = 0

# どう書いたら良いでしょうか。

puts "結果: #{result}" #  26 が出るはず
```

# 配列が入っている配列の中身を合計する

```rb
array =  [[4], [6], [7], [9]]
result = 0

# どう書いたら良いでしょうか。

puts "結果: #{result}" #  26 が出るはず
```

# 複数の処理を一度に行う

```rb
array =  [{ value: 4, xxx: 1}, {value: 6, xxx: 3}, {value: 7, xxx: 9}, {value: 9, xxx: 4}]
value_result = 0
xxx_result = 0

# どう書いたら良いでしょうか。

puts "結果: #{value_result}" #  26 が出るはず
puts "結果: #{xxx_result}" #  17 が出るはず
```
# 複雑な構造から値を合計する

value の中の 配列に含まれる valueの値を合計してください。

```rb
array =  [
  { test: 123, value: [{ value: 1 }, { value: 2 }] },
  { test: 444, value: [{ value: 2 }, { value: 4 }] },
  { test: 566, value: [{ value: 3 }, { value: 4 }] }
]
result = 0

# どう書いたら良いでしょうか。

puts "結果: #{result}" #  16 が出るはず
```

# 文字列の長さを合計する

```rb
len = "あいう".size
puts len # 文字列の長さとして 3 が出力されます
```
この法則を利用して、文字列の長さを合計しましょう

```rb
array =  [{ value: 4, xxx: "ああ"}, {value: 6, xxx: "本日は"}, {value: 7, xxx: "晴天"}, {value: 9, xxx: "ですか？"}]
value_result = 0
xxx_result = 0

# どう書いたら良いでしょうか。

puts "結果: #{value_result}" #  26 が出るはず
puts "結果: #{xxx_result}" #  11 が出るはず
```

**Comment by ms2sato** [comment]
@hamika #5 が難しそうならまずこちらをやってみましょう。

**Comment by hamika** [comment]
@ms2sato 
できました。 3f055d5 
配列の中のハッシュを取り出すのに手こずりました。

**Comment by hamika** [comment]
@ms2sato 以下の課題をやっていて思ったのですが、
```ruby
# 文字列の長さを合計する
array = [{ value: 4, xxx: "ああ" }, { value: 6, xxx: "本日は" }, { value: 7, xxx: "晴天" }, { value: 9, xxx: "ですか？" }]

puts "#{array[0][:xxx].size}, #{array[0][:xxx]}"
puts "#{array[1][:xxx].size}, #{array[1][:xxx]}"

puts "#{array[0][:value].size}, #{array[0][:value]}"
puts "#{array[1][:value].size}, #{array[1][:value]}"
```
```
2, ああ
3, 本日は
8, 4
8, 6
```
のように `array[0][:value].size` や `array[1][:value].size` を指定しても常に `8` が返ってきます。これはArrayクラスのIntegerに対してsizeメソッドを使っているから `8` が返ってくるのでしょうか? 課題からは脱線するのかも知れないですが、理解しておいた方がいいのかもと思ったので。お手隙の際に教えてください。よろしくお願いいたします。

**Comment by ms2sato** [comment]
@hamika 

> ArrayクラスのIntegerに対してsizeメソッドを使っているから 8 が返ってくる

概ね理解合っています。ただし、「Arrayクラスの」 ではないです。 Integer型が持っている性質です。
同じメソッドでも、どの型に対して利用するかで結果が変わります（Stringの場合には文字数でしたね）。

数値が持っているsizeについては、ほとんどの場合8が返ってくると思います。これはコンピュータについてよく勉強するとわかるのですが、数字が8バイトという単位で保存されていることを示します（ここはそんなにこだわらなくて大丈夫）。
https://docs.ruby-lang.org/ja/latest/method/Fixnum/i/size.html
