### ISSUE TITLE
演習問題（ミニツク）

### ISSUE THREAD

**Issue by ms2sato** [hamika/ocs#7]
時間ができたらこれをやる

- [x] http://www.minituku.net/exercises/65255135.html
- [x] http://www.minituku.net/exercises/465034482.html
- [ ] http://www.minituku.net/exercises/547047470.html
- [ ] http://www.minituku.net/exercises/129583522.html
- [x] http://www.minituku.net/exercises/269035703.html

**Comment by hamika** [comment]
@ms2sato 

問題: 標準出力へ文字を出力する簡単なプログラムを書いてみましょう。

http://www.minituku.net/exercises/65255135.html

```ruby
irb(main):001:0> puts "foo"
foo
=> nil
irb(main):002:0> puts "bar"
bar
=> nil
irb(main):003:0> puts 'baz'
baz
=> nil
```

**Comment by hamika** [comment]
> 3.2.5 型と自動変換
Rubyは型を厳密に区別・・・というより数値もオブジェクトなので特定のクラスに属することになるから明示的な変換が必要となる。

**Comment by hamika** [comment]
@ms2sato 

問題: 1から100までの数値を合計してください。そして、その合計値を標準出力に出力してください。

http://www.minituku.net/exercises/465034482.html

```ruby
result = 0

(1..100).each do |math|
  result += math
end

puts result #=> 5050
```

**Comment by ms2sato** [comment]
ここまではよく書けてますね！バッチリです。

**Comment by hamika** [comment]
@ms2sato 

問題: コード例で呼び出しているbuy_ticketsメソッドを定義しましょう。buy_ticketsメソッドの処理は、出力例から推測してください。

```ruby
# コード例:
buy_tickets("Sam", "Dave", "David")
buy_tickets("John", "Paul", "Ringo", "George")

# 出力例:
#=> Buying a ticket for Sam.
#=> Buying a ticket for Dave.
#=> Buying a ticket for David.
#=> Buying a group ticket for John, Paul, Ringo, George.
```

http://www.minituku.net/exercises/269035703.html

```ruby
# pattern 1
def buy_tickets(*menbers)
  if menbers.size > 3
    puts "Buying a group ticket for #{ menbers.join(', ') }."
  else
    menbers.each do |menber|
      puts "Buying a ticket for #{ menber }."
    end
  end
end

# pattern 2
def buy_tickets(*menbers)
  if menbers.size > 3
    puts "Buying a group ticket for #{ menbers.join(', ') }."
  else
    menbers.map do |menber|
      puts "Buying a ticket for #{ menber }."
    end
  end
end

buy_tickets('Sam', 'Dave', 'David') 
buy_tickets('John', 'Paul', 'Ringo', 'George')

# 出力結果:    # eachでもmapでも結果は同じ
#=> Buying a ticket for Sam.
#=> Buying a ticket for Dave.
#=> Buying a ticket for David.
#=> Buying a group ticket for John, Paul, Ringo, George.
```

**Comment by hamika** [comment]
@ms2sato 
問題: コード例で生成している各オブジェクトごとにlifeメソッドを定義しましょう。lifeメソッドのおこなう処理は、コメントアウトされている出力例から推測してください。

```ruby
# 以下のコードがコメント部分の通りの出力となるように(A)の部分に当てはまる適切なコードを書いてください。

class Planet
  def life?
    puts "Who knows?"
  end
end

# # # (A) # # #

pluto = Planet.new()
earth = Planet.new()
mars  = Planet.new()
 
pluto.life?()  #=> Probably not.
earth.life?()  #=> Positively!
mars.life?()   #=> Who knows?
```

http://www.minituku.net/exercises/228585781.html

```ruby
class Planet
  def life?
    puts 'Who knows?'
  end
end

pluto = Planet.new
earth = Planet.new
mars  = Planet.new

def earth.life?
puts 'Positively!'
end

def pluto.life?
  puts 'Probably not.'
end

pluto.life? #=> Probably not.
earth.life? #=> Positively!
mars.life?  #=> Who knows?
```

**Comment by ms2sato** [comment]
@hamika 
https://github.com/hamika/ocs/issues/7#issuecomment-322954410
こちらの課題、map を使った意図を教えて欲しいですー。
結果は大丈夫そうだし、類推するところも「3より多ければ」で合っていると思います。さすが！

https://github.com/hamika/ocs/issues/7#issuecomment-322971219
こちらは難しかったんじゃなかろうか。多分この回答で使う機能を知らないですよね（実は現場でもあまり使いません。ただ知っているとすごく便利な時もあるんです）。よく正解できました！

**Comment by ms2sato** [comment]
http://www.minituku.net/exercises/767771771.html
http://www.minituku.net/exercises/820836204.html

上記は難しいと思うので、時間のあるときにやると良いと思います！

**Comment by hamika** [comment]
@ms2sato 
[#7 (comment)](https://github.com/hamika/ocs/issues/7#issuecomment-322954410)
こちらについてはeachではじめ動きを確認して、ループさせる対象が一つだしmapでも挙動が一緒かなと思って試してみただけです。特別理由がなければ、やっぱりeachを使うべきなのですかね。

[#7 (comment)](https://github.com/hamika/ocs/issues/7#issuecomment-322971219)
こちらは全然意味わからなかったのですが [このページ](https://www.sist.ac.jp/~suganuma/home/Ruby/syntax/Class/Class.htm#sp) を見て、もしかしたら同じ書き方で通るかもと思って書いたら動いた感じです。なので表面的なことも理解していないと思いますし、たまたま動かせた感じです。

**Comment by ms2sato** [comment]
@hamika mapはあくまで「 配列から新しい配列を作るため 」 という目的のもとで使用するべきです。何回も繰り返したいだけであれば each を使うという使い分けをしましょう。

> もしかしたら同じ書き方で通るかも

この勘はとてもいいですね。経験としては覚えておいてくださいー。

**Comment by ms2sato** [comment]
Closeします。時間ある時にこの手の頭の体操はしてみましょう！
