### ISSUE TITLE
演習課題 vol. 2

### ISSUE THREAD

**Issue by ms2sato** [hamika/ocs#8]
# 配列の個数を数える

以下の 1、2をやりましょう。この二つが一緒に計算できると良いです。ただし、arrayの中身を増やしたりした時に、自分の書いたコードを修正しなくても良いように書いてください（ハードコーディングしてはダメということです）。

1. array の中にある、要素の個数を数えてputsしましょう（合計 11）
2. array の中にある、数字の合計を出してputsしましょう（合計 39）

```rb
array =  [
  [1, 5, 6, 8],
  [3, 3, 1,  1,  2],
  [4, 5]
]

# どう書いたら良いでしょうか。
```

# 文字を連結する

下記の配列の中の文字列を連結して「いろはにほへとちりぬるを」を完成してputsしてください。

```rb
array =  [
  ['いろ', 'は', 'にほへ'],
  ['と', 'ちり'],
  [ 'ぬ',  'る',  'を']
]

# どう書いたら良いでしょうか。
```

# 一定の条件の場合だけ合計する（数値）

1. 偶数の場合だけ加算して、結果をputsしてください
2. 偶数の値だけが入った新しい配列を array2 という変数で作ってください

```rb
array =  [
  [1, 5, 6, 8],
  [3, 3, 1,  1,  2],
  [4, 5]
]

# どう書いたら良いでしょうか。
```

# 一定の条件の場合だけ合計する（文字列）

下記の配列の中の文字列を連結して「いろはにほへとちりぬるを」を完成してputsしてください。途中に入り込んでいる数値を連結しない方法を考えましょう。

```rb
array =  [
  ['いろ', 0,  'は', 4, 'にほへ'],
  ['と', 9, 'ちり'],
  [ 'ぬ',  'る', 10,  'を']
]

# どう書いたら良いでしょうか。
```

# ハッシュのキーを使う

下記のハッシュの中からキーだけ取り出して「佐藤,鈴木,田中」とputsしてください。
同様に値だけを取り出して「1,2,3」とputsしてください。

```rb
hash = {
  '佐藤' => 1,
  '鈴木' => 2,
  '田中' => 3
}
```

**Comment by hamika** [comment]
@ms2sato **一定の条件の場合だけ合計する（数値）** の課題がうまく解けません。

**Comment by ms2sato** [comment]
@hamika `一定の条件の場合だけ合計する（数値）` 

ヒント： 1.class.name　や 'a'.class.name を利用できませんか？

実はこのやり方は素晴らしく良いわけではないのですが、今回鍛えたい考え方にはうまく使えるので課題に入れています。チャレンジしてみてください。

だいぶ自力で考えて動かせるようになってきたと思います。もう少し繰り返しましょう。

**Comment by hamika** [comment]
@ms2sato 
全問解けましたーーー！！=> c3ac6f9
お手隙の際にご確認よろしくお願いいたします!
